server {
    listen 80;

    location /rest/v1/ {
        proxy_pass http://rest:3000/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
        proxy_set_header apikey $http_apikey;

        proxy_hide_header Access-Control-Allow-Origin;
        proxy_hide_header Access-Control-Allow-Methods;
        proxy_hide_header Access-Control-Allow-Headers;
        proxy_hide_header Access-Control-Expose-Headers;

        # CORS
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, POST, PATCH, PUT, DELETE, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Authorization, Content-Type, Accept, Prefer, apikey" always;
        add_header Access-Control-Expose-Headers "Content-Range, Range" always;

        if ($request_method = OPTIONS) {
            return 204;
        }
    }
}
